services:
  - type: web
    name: flask-todo
    env: python
    repo: https://github.com/vihansr/To-Do-List
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        value: postgres://todo_7wei_user:TFcuGaOR0spLllV2ou5qaQ7FaXnmO3NG@dpg-cv7h2ftds78s7395rdgg-a.oregon-postgres.render.com/todo_7wei
      - key: SECRET_KEY
        value: "eihfn983n2c9"
